<a href="https://colab.research.google.com/github/AJAY-22/Python_Practicals/blob/main/LabManual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1] Intro to Data Types, Operations and conditional statements.
---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## 1.1] Write aprogram to print “Hello World”.

In [ ]:
print("Hello World")

Hello World


## 1.2] Write a program to find maximum number out of 3 numbers.


In [ ]:
numbers=[11, 34, 5]

'''For user input'''
for x in range(len(numbers)):
    inp = float(input(f'Enter #{x+1} '))
    numbers[x] = inp

max=numbers[0]

for x in numbers:
    if max<x:
        max=x

print("Max number is :" ,max)

Enter #1 10
Enter #2 5
Enter #3 86
Max number is : 86.0


## 1.3] Write a program to swap the values of two variables without using temporary variable.

In [ ]:
a, b = 1, 2
print('Before swapping \na :', a, '\nb :', b)
a, b = b, a
print('\nAfter swapping \na :', a, '\nb :', b)

Before swapping 
a : 1 
b : 2

After swapping 
a : 2 
b : 1


## 1.4] Write a program to implement calculator.

In [ ]:
from IPython.display import clear_output 



while True:
    print('1) Add\n2) Subtract\n3) Multiply\n4) Divide\n5) Exit')
    choice = int(input('Enter your choice '))
    clear_output()
    
    if choice in [1, 2, 3, 4]:
        if choice is 1:
            print('ADDITION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '+', b, '=', a+b)
        
        if choice is 2:
            print('SUBTRACTION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '-', b, '=', a-b)

        if choice is 3:
            print('MULTIPLICATION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '*', b, '=', a*b)
        
        if choice is 4:
            print('DIVISION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '/', b, '=', a/b)

    elif choice is 5:
        break
    else:
        clear_output()
        print('Invalid Input\n')

## 1.5] Write a Python program to calculate the sum of the digits in an integer.

In [ ]:
num = int(input("Your number (must be 4 digit) : "))
x = num//1000
x1 = (num - x*1000)//100
x2 = (num - x*1000 - x1*100)//10
x3 = (num - x*1000 - x1*100 - x2*10)

print(f'sum of number\'s digits : {x+x1+x2+x3}')

Your number (must be 4 digit) : 5588
sum of number's digits : 26


# 2] Introduction to Control Structures and Functions
---

## 2.1] Write  a  program  to  find factorial  of  a  given  number  using  iterative  and recursive function.

### 2.1.1] Iterative method to find factorial of given number.

In [ ]:
n=int(input("Enter Number : "))
fact=1

while(n>0):
  fact*=n
  n-=1

print(fact)

Enter Number : 10
3628800


### 2.1.2] Recursive method to find factorial of given number.

In [ ]:
n=int(input('Enter number : '))

def find_fac(num):
  if num==0:
    return 1
  else:
    return num*find_fac(num-1)

print(find_fac(n))

Enter number : 5
120


## 2.2] Write a program to check whether a given number is prime or not.

In [ ]:
n=int(input('Enter Number :'))

def is_prime(num):
  flag=0
  for x in range(1, num+1):
    if num%x==0:
      flag+=1

  if flag==2:
    print(num, 'is Prime')
  else:
    print(num, 'is not prime')

is_prime(n)


Enter Number :10
10 is not prime


## 2.3] Write a program to print Fibonacci series upto n. 

In [ ]:
n=int(inptut('Enter number :'))

for x in range(n):
  

## 2.4] Write a program which takes a sentence from user and calculates number of digits, letters, uppercase letters, lowercase letter and spaces in sentence.

## 2.5] Reversing a given string.

# 3] Study of List and Tuple
---

## 3.1] Write a program to remove duplicates from list.

In [ ]:
myList = ['One', 'two', 'two', 'three', 'three', 'three', 'four']
unique = []

print('original list :', myList)

for el in myList:
    if el not in unique:
        unique.append(el)

print('without duplicates :', unique)

original list : ['One', 'two', 'two', 'three', 'three', 'three', 'four']
without duplicates : ['One', 'two', 'three', 'four']


## 3.2] Write a program to find frequency of elements of list.

In [ ]:
my_list = [7, 2, 6, 5, 8, 7, 8, 3, 2, 3]
unique = []
for el in my_list:
    if el not in unique:
        unique.append(el)

for el in unique:
    print('Frequency of ', el, 'in my_list :', my_list.count(el))

Frequency of  7 in my_list : 2
Frequency of  2 in my_list : 2
Frequency of  6 in my_list : 1
Frequency of  5 in my_list : 1
Frequency of  8 in my_list : 2
Frequency of  3 in my_list : 2


## 3.3] Write a program to sort given list.

In [ ]:
print('Original :', my_list)
my_list.sort()
print('Ascending :', my_list)
print('Descending :', my_list[::-1])

Original : [7, 2, 6, 5, 8, 7, 8, 3, 2, 3]
Ascending : [2, 2, 3, 3, 5, 6, 7, 7, 8, 8]
Descending : [8, 8, 7, 7, 6, 5, 3, 3, 2, 2]


## 3.4] Write a program to find minimum and maximumvalue in list of tuples.

In [ ]:
my_tuple_list = [(22, 1), (16, 3), (27, 11), (29, 9)]
print('Original list :', my_tuple_list)

zeroth = [tup[0] for tup in my_tuple_list]
first = [tup[1] for tup in my_tuple_list]

res1 = min(zeroth), max(zeroth)
res2 = min(first), max(first)
print('\nmin at 0th index of tuples :', res1[0], '\nmax at 0th index of tuples :', res1[1])
print('\nmin at 1st index of tuples :', res2[0], '\nmax at 1st index of tuples :', res2[1])

Original list : [(22, 1), (16, 3), (27, 11), (29, 9)]

min at 0th index of tuples : 16 
max at 0th index of tuples : 29

min at 1st index of tuples : 1 
max at 1st index of tuples : 11


## 3.5] Write a program to remove an element from tuple. 

In [ ]:
myTuple = ('one', 'two', 'three', 'four', 'four', 'five')
print(myTuple)

('one', 'two', 'three', 'four', 'four', 'five')


In [ ]:
# Removing element using slicing
myTuple = myTuple[:3] + myTuple[4:]
print(myTuple)

('one', 'two', 'three', 'four', 'five')


In [ ]:
# Removing using typecast
myList = list(myTuple)
myList.remove('four')
myTuple = myList
print(myTuple)

['one', 'two', 'three', 'five']


# 4] Study of Dictionary
---

## 4.1] Write a program to map 2 lists into a dictionary.

In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = ['one', 'two', 'three', 'four', 'five']

d1 = dict(zip(l1, l2))

print(d1)


{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}


## 4.2] Write  a  program  to  generate  dictionary  of  frequency  of  alphabets  of  given string.

In [ ]:
string = str(input("Enter string : "))
keys = []
values = []

for el in string:
    if el not in keys:
        keys.append(el)
        values.append(string.count(el))

d1 = dict(zip(keys, values))
print(d1)

Enter string : ajay pathak kamleshbhai
{'a': 6, 'j': 1, 'y': 1, ' ': 2, 'p': 1, 't': 1, 'h': 3, 'k': 2, 'm': 1, 'l': 1, 'e': 1, 's': 1, 'b': 1, 'i': 1}


## 4.3] Write a Python program to sum all the items in a dictionary.

In [ ]:
d1 = {'hundred': 100, 'sixty': -60, 'twenty': -20, 'two': 2}
sum = int(sum(d1.values()))
print(sum)

22


## 4.4]Create a dictionary where keys are name of students and values are another dictionary containing semester, age and cpi of that student. 


In [ ]:
student_info = {'Ak': {'semester': 5,
                       'age': 19,
                       'cpi': 8.2},
                'Aj': {'semester': 5,
                       'age': 20,
                       'cpi': 9.0}}

### 4.4.1] Print all the names of students.

In [ ]:
print(student_info)

{'Ak': {'semester': 5, 'age': 19, 'cpi': 8.2}, 'Aj': {'semester': 5, 'age': 20, 'cpi': 9.0}}


### 4.4.2] Print only names of students

In [ ]:
print(student_info.keys())

dict_keys(['Ak', 'Aj'])


### 4.4.3] Print the name of student having highest CPI 

In [ ]:
names = [x for x in student_info]

cpis = [student_info.get(name).get('cpi') for name in names]
highest = max(cpis)

pos = cpis.index(highest)
print('Student havning highest cpi :', names[pos])


Student havning highest cpi : Aj


## 4.5] Nested Dictionary Practice


### 4.5.1] Creating a Nested Dictionary

In [ ]:
faculty = {1: {'name': 'Akj', 'contact': 1234567890, 'city': 'city1'},
           2: {'name': 'sk', 'contact': 9987654321, 'city': 'city1'},
           3: {'name': 'ap', 'contact': 1234509876, 'city': 'city2'}}

print(faculty)

{1: {'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}, 2: {'name': 'sk', 'contact': 9987654321, 'city': 'city1'}, 3: {'name': 'ap', 'contact': 1234509876, 'city': 'city2'}}


### 4.5.2] Accessing elements

In [ ]:
print(faculty[1]['name'])
print(faculty[2]['contact'])
print(faculty[3]['city'])

for x in faculty.keys():
  print(faculty[x])

Akj
9987654321
city2
{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'ap', 'contact': 1234509876, 'city': 'city2'}


### 4.5.3] Adding element 

In [ ]:
faculty[4] = {}
faculty[4]['name'] = 'SP'
# faculty[4]['contact'] = 5432109876
faculty[4]['city'] = 'city2'

faculty[5] = {'name': 'LK', 'contact': 5647382910, 'city': 'city2', 'married': 'yes'}

for x in faculty.keys():
  print(faculty[x])

{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'ap', 'contact': 1234509876, 'city': 'city2'}
{'name': 'SP', 'city': 'city2'}
{'name': 'LK', 'contact': 5647382910, 'city': 'city2', 'married': 'yes'}


### 4.5.4] Deleting elemets

In [ ]:
del faculty[5]['married']
del faculty[3], faculty[4]

for key in faculty.keys():
  print(faculty[key])


{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'LK', 'contact': 5647382910, 'city': 'city2'}


### 4.5.5] Iterating through Nested Dictionary

In [ ]:
for id, value in faculty.items():
  print('Faculty ID =', id)

  for key in value:
    print(key, '=', value[key])
  print('\n')

Faculty ID = 1
name = Akj
contact = 1234567890
city = city1


Faculty ID = 2
name = sk
contact = 9987654321
city = city1


Faculty ID = 5
name = LK
contact = 5647382910
city = city2




# 5] Write a python program to explore various types of files (csv, excel etc.) using pandas.
---

## Importing Pandas and defining data.

First of all ,

To use pandas library, we need to install pandas and import it.

Conventionally we use alias 'pd' for pandas library 

In [1]:
import pandas as pd

Next cell defines data 

we are using data of different countries ( such as population, GDP, Continent etc.) 

In [2]:
contries_data = {
    'CHN': {'COUNTRY': 'China', 'POP': 1_398.72, 'AREA': 9_596.96,
            'GDP': 12_234.78, 'CONT': 'Asia'},
    'IND': {'COUNTRY': 'India', 'POP': 1_351.16, 'AREA': 3_287.26,
            'GDP': 2_575.67, 'CONT': 'Asia', 'IND_DAY': '1947-08-15'},
    'USA': {'COUNTRY': 'US', 'POP': 329.74, 'AREA': 9_833.52,
            'GDP': 19_485.39, 'CONT': 'N.America',
            'IND_DAY': '1776-07-04'},
    'IDN': {'COUNTRY': 'Indonesia', 'POP': 268.07, 'AREA': 1_910.93,
            'GDP': 1_015.54, 'CONT': 'Asia', 'IND_DAY': '1945-08-17'},
    'BRA': {'COUNTRY': 'Brazil', 'POP': 210.32, 'AREA': 8_515.77,
            'GDP': 2_055.51, 'CONT': 'S.America', 'IND_DAY': '1822-09-07'},
    'PAK': {'COUNTRY': 'Pakistan', 'POP': 205.71, 'AREA': 881.91,
            'GDP': 302.14, 'CONT': 'Asia', 'IND_DAY': '1947-08-14'},
    'NGA': {'COUNTRY': 'Nigeria', 'POP': 200.96, 'AREA': 923.77,
            'GDP': 375.77, 'CONT': 'Africa', 'IND_DAY': '1960-10-01'},
    'BGD': {'COUNTRY': 'Bangladesh', 'POP': 167.09, 'AREA': 147.57,
            'GDP': 245.63, 'CONT': 'Asia', 'IND_DAY': '1971-03-26'},
    'RUS': {'COUNTRY': 'Russia', 'POP': 146.79, 'AREA': 17_098.25,
            'GDP': 1_530.75, 'IND_DAY': '1992-06-12'},
    'MEX': {'COUNTRY': 'Mexico', 'POP': 126.58, 'AREA': 1_964.38,
            'GDP': 1_158.23, 'CONT': 'N.America', 'IND_DAY': '1810-09-16'},
    'JPN': {'COUNTRY': 'Japan', 'POP': 126.22, 'AREA': 377.97,
            'GDP': 4_872.42, 'CONT': 'Asia'},
    'DEU': {'COUNTRY': 'Germany', 'POP': 83.02, 'AREA': 357.11,
            'GDP': 3_693.20, 'CONT': 'Europe'},
    'FRA': {'COUNTRY': 'France', 'POP': 67.02, 'AREA': 640.68,
            'GDP': 2_582.49, 'CONT': 'Europe', 'IND_DAY': '1789-07-14'},
    'GBR': {'COUNTRY': 'UK', 'POP': 66.44, 'AREA': 242.50,
            'GDP': 2_631.23, 'CONT': 'Europe'},
    'ITA': {'COUNTRY': 'Italy', 'POP': 60.36, 'AREA': 301.34,
            'GDP': 1_943.84, 'CONT': 'Europe'},
    'ARG': {'COUNTRY': 'Argentina', 'POP': 44.94, 'AREA': 2_780.40,
            'GDP': 637.49, 'CONT': 'S.America', 'IND_DAY': '1816-07-09'},
    'DZA': {'COUNTRY': 'Algeria', 'POP': 43.38, 'AREA': 2_381.74,
            'GDP': 167.56, 'CONT': 'Africa', 'IND_DAY': '1962-07-05'},
    'CAN': {'COUNTRY': 'Canada', 'POP': 37.59, 'AREA': 9_984.67,
            'GDP': 1_647.12, 'CONT': 'N.America', 'IND_DAY': '1867-07-01'},
    'AUS': {'COUNTRY': 'Australia', 'POP': 25.47, 'AREA': 7_692.02,
            'GDP': 1_408.68, 'CONT': 'Oceania'},
    'KAZ': {'COUNTRY': 'Kazakhstan', 'POP': 18.53, 'AREA': 2_724.90,
            'GDP': 159.41, 'CONT': 'Asia', 'IND_DAY': '1991-12-16'}
}

columns = ('COUNTRY', 'POP', 'AREA', 'GDP', 'CONT', 'IND_DAY')

## Using pandas DataFrame 

DataFrame is pandas way of storing and visiualizing data

to convert our dictionary ( or any DataStructure ) in pandas DataFrame object , we use ```pd.DataFrame(data_variable_name)```.

It returns our data in DataFrame format , so we need to store it in some variable.

In [14]:
# We stored our data in 'contries_data' variable
# Let's store the returned DataFrame Object in df (DataFrame)
df = pd.DataFrame(contries_data)

# we can use print function
print(df)

             CHN         IND         USA  ...         CAN        AUS         KAZ
COUNTRY    China       India          US  ...      Canada  Australia  Kazakhstan
POP      1398.72     1351.16      329.74  ...       37.59      25.47       18.53
AREA     9596.96     3287.26     9833.52  ...     9984.67    7692.02      2724.9
GDP      12234.8     2575.67     19485.4  ...     1647.12    1408.68      159.41
CONT        Asia        Asia   N.America  ...   N.America    Oceania        Asia
IND_DAY      NaN  1947-08-15  1776-07-04  ...  1867-07-01        NaN  1991-12-16

[6 rows x 20 columns]


In [15]:
# We are not getting whole data , also representation is not good 
# Let's use something better
# We can directly call our dataframe object and it will print the data 
df

CHN         IND         USA  ...         CAN        AUS         KAZ
COUNTRY    China       India          US  ...      Canada  Australia  Kazakhstan
POP      1398.72     1351.16      329.74  ...       37.59      25.47       18.53
AREA     9596.96     3287.26     9833.52  ...     9984.67    7692.02      2724.9
GDP      12234.8     2575.67     19485.4  ...     1647.12    1408.68      159.41
CONT        Asia        Asia   N.America  ...   N.America    Oceania        Asia
IND_DAY      NaN  1947-08-15  1776-07-04  ...  1867-07-01        NaN  1991-12-16

[6 rows x 20 columns]

In [16]:
# Much better but , Let's also transpose it. To make it more intuitive. 
df = pd.DataFrame(contries_data, index=columns).T # Notice, using .T results in transposing the data
df

COUNTRY      POP     AREA      GDP       CONT     IND_DAY
CHN       China  1398.72  9596.96  12234.8       Asia         NaN
IND       India  1351.16  3287.26  2575.67       Asia  1947-08-15
USA          US   329.74  9833.52  19485.4  N.America  1776-07-04
IDN   Indonesia   268.07  1910.93  1015.54       Asia  1945-08-17
BRA      Brazil   210.32  8515.77  2055.51  S.America  1822-09-07
PAK    Pakistan   205.71   881.91   302.14       Asia  1947-08-14
NGA     Nigeria   200.96   923.77   375.77     Africa  1960-10-01
BGD  Bangladesh   167.09   147.57   245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.2  1530.75        NaN  1992-06-12
MEX      Mexico   126.58  1964.38  1158.23  N.America  1810-09-16
JPN       Japan   126.22   377.97  4872.42       Asia         NaN
DEU     Germany    83.02   357.11   3693.2     Europe         NaN
FRA      France    67.02   640.68  2582.49     Europe  1789-07-14
GBR          UK    66.44    242.5  2631.23     Europe         NaN
ITA       Italy    60.36   301.34  1943.84     Europe         NaN
ARG   Argentina    44.94   2780.4   637.49  S.America  1816-07-09
DZA     Algeria    43.38  2381.74   167.56     Africa  1962-07-05
CAN      Canada    37.59  9984.67  1647.12  N.America  1867-07-01
AUS   Australia    25.47  7692.02  1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.9   159.41       Asia  1991-12-16

## Using Pandas to convert data in various format types.

### CSV Format type

Use ```to_csv('file_name.csv')``` to convert DataFrame in CSV format

In [17]:
# Let's convert our contries_data into csv format
# our contries data is stored in df variable 
df.to_csv('contries_data.csv')  # NOTE : we give the filename whatever we like but its extension must be .csv

# if you check your colab folder , 
# you can see contries_data.csv file.

Use ```pd.read_csv(filename)``` to read csv file.

This function returns DataFrame object , so we need to store it in some variable.

In [22]:
df = pd.read_csv('contries_data.csv') # NOTE : Only file with extension .csv can be read. 
# Now that it returns DataFrame object , we can print it like below
df

Unnamed: 0     COUNTRY      POP      AREA       GDP       CONT     IND_DAY
0         CHN       China  1398.72   9596.96  12234.78       Asia         NaN
1         IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
2         USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
3         IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
4         BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
5         PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
6         NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
7         BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
8         RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
9         MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
10        JPN       Japan   126.22    377.97   4872.42       Asia         NaN
11        DEU     Germany    83.02    357.11   3693.20     Europe         NaN
12        FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
13        GBR          UK    66.44    242.50   2631.23     Europe         NaN
14        ITA       Italy    60.36    301.34   1943.84     Europe         NaN
15        ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
16        DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
17        CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
18        AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
19        KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

In [26]:
# Let's make column that represents country's abbreviated names as a index column
# in read_csv fumction we can give index which represents index
# in our case first column represents index , so it's 0th column in DataFrame
df = pd.read_csv('contries_data.csv', index_col=0) 
df

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia         NaN
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia         NaN
DEU     Germany    83.02    357.11   3693.20     Europe         NaN
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe         NaN
ITA       Italy    60.36    301.34   1943.84     Europe         NaN
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### Excel format type

To convert to and read from Excel files we need to install some packages. 
- xlwt
- openpyxl
- xlswriter
- xlrd

NOTE : Below cell gives command to install these in one line only

We can always install only one package and not others if not required

In [27]:
pip install xlwt openpyxl xlsxwriter xlrd

In [10]:
df.to_excel('contries_data.xlsx')

# We can find this file in our colab folder

In [11]:
df = pd.read_excel('contries_data.xlsx', index_col=0)
df

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia         NaN
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia         NaN
DEU     Germany    83.02    357.11   3693.20     Europe         NaN
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe         NaN
ITA       Italy    60.36    301.34   1943.84     Europe         NaN
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### JSON format type

In [12]:
df_json = df.to_json('contries_data.json')

# New jason file will be added in your directory
pd.read_json('contries_data.json')

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia        None
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75       None  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia        None
DEU     Germany    83.02    357.11   3693.20     Europe        None
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe        None
ITA       Italy    60.36    301.34   1943.84     Europe        None
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania        None
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### HTML format type

In [13]:
df_html = df.to_html('contries_data.html')

# New jason file will be added in your directory
pd.read_html('contries_data.html')

[   Unnamed: 0     COUNTRY      POP      AREA       GDP       CONT     IND_DAY
 0         CHN       China  1398.72   9596.96  12234.78       Asia         NaN
 1         IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
 2         USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
 3         IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
 4         BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
 5         PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
 6         NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
 7         BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
 8         RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
 9         MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
 10        JPN       Japan   126.22    377.97   4872.42       Asia         NaN
 11        DEU     Germany    83.02    357.11   3693

# 6] Write python programs demonstrating different functions for preprocessing the data. 
---

## NumPy Random

In [28]:
import numpy as np

In [31]:
r1 = np.random.rand()
# Returns random float between 0 to 1
print(r1)

0.27535029647508846


In [34]:
random_mat = np.random.rand(2, 2)
# returns matrix of shape given in argument,
# with all the elements having random value between 0 to 1
print(random_mat)

[[0.45837653 0.89238328]
 [0.35232794 0.55125071]]


In [46]:
r1 = np.random.randint(11, 20, 20)
# In randint function we can give range for the random number
# With the last argument we can decide the length of array
print(r1)

# then we can reshape this array and use it as matrix 
r1_mat = r1.reshape(5, 4)
# NOTE reshape returns matrix of shape we give , it doesn't change r1 it self
print('r1 still same :', r1)
print('r1_mat :\n', r1_mat)

[11 12 11 13 13 15 15 17 18 19 14 17 18 12 13 11 11 13 19 17]
r1 still same : [11 12 11 13 13 15 15 17 18 19 14 17 18 12 13 11 11 13 19 17]
r1_mat :
 [[11 12 11 13]
 [13 15 15 17]
 [18 19 14 17]
 [18 12 13 11]
 [11 13 19 17]]


## String Slicing

In [47]:
string_name = 'The Girl With The Dragon Tattoo'
print(string_name)

The Girl With The Dragon Tattoo


In [64]:
# Let's print first 3 characters
print(string_name[0:2])
# Remeber the index given as a stop argument means 
# that we need to stop before that index 
# in our case it will stop after 1st index
# Thus, not printing the 2nd index

# Let's print first 3 characters properly this time
print(string_name[0:3])

Th
The


In [66]:
# not giving start argument results as 0th index 
print(string_name[:3])

The


In [68]:
# not giving stop argument results as length of variabl
print(string_name[4:])

Girl With The Dragon Tattoo


In [69]:
# Using negative index we can refer indeces counting from last element 
# last element is (length-1)th index or
# it's simply -1 index
# Let's print last 6 character
print(string_name[-6:])

# this prints starting from 6th last index to end of the list

Tattoo


In [71]:
# similarly , we can use negative index as stop argument 
print(string_name[-13:-7])

Dragon


In [75]:
# Let's use step argument
# It decides how many steps to take
# To better understand let's have different example
different = 'a b c d e'
print(different[::2])
# every time it will take 2 steps instead of 1 (1 is default)
# this skipping every space in between

abcde


In [55]:
# We can not pass step size as 0 
print(string_name[::0])

ValueError: ignored

In [76]:
# Negative step size means traversing the list / string in reverse order
name = '123456789'
print(name[::-1])

987654321


In [79]:
# We can have negative index size bigger than 1 , 
# which will result in taking more than 1 step in reverse order
diff = 'a b_c d e_f g'
print(diff[::-3])

g_d_a


## String print format

In [84]:
text = 'This is {}'
print(text.format('formatting'))
# format function replaces '{}' (braces) with the string given as an argument
# and returns new string.
# meaning it does not change string itself.
print(text)

This is formatting
This is {}


In [85]:
# as it returns string , we can store it in some variable
formatted_name = text.format('America')
print(formatted_name)

This is America


In [92]:
# Multiple formatting 
other_text = 'Hello, My name is {}.\nI am {}'
formatted_text = other_text.format('Zoozzy', 'ROBOT')
print(formatted_text)

# Note : arguments are postitional , 
# first argument replaces first braces and so on ....

Hello, My name is Zoozzy.
I am ROBOT


In [93]:
# Not providing argument results in error
print(other_text.format('Ajay'))

IndexError: ignored

In [98]:
# We can specify order of parameters 
param_text = 'Last name : {2}, second name : {1}, first name : {0}'
print(param_text.format('ajay', 'k.', 'Pathak'))

# here, format takes 0th index of tuple we gave and 
# replaces it with the braces having 0 in it (i.e, {0}), so on for others too.

Last name : Pathak, second name : k., first name : ajay


In [102]:
# instead of numbers we can provide strings
full_name = 'i am {first_name} from {country} , {state}'
print(full_name.format(first_name='Ajay', state='Gujarat', country='India'))

# see, It replaces all the arguments with appropiate strings.

i am Ajay from India , Gujarat


## formatting decimal values

In [103]:
value = '1234.5678'
print(value)

1234.5678


In [ ]:
print('{v:4.7}'.format(v=value))