<a href="https://colab.research.google.com/github/AJAY-22/Python_Practicals/blob/main/LabManual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1] Intro to Data Types, Operations and conditional statements.
---


In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 1.1] Write aprogram to print “Hello World”.

In [15]:
print("Hello World")

Hello World


## 1.2] Write a program to find maximum number out of 3 numbers.


In [55]:
numbers=[11, 34, 5]

'''For user input'''
for x in range(len(numbers)):
    inp = float(input(f'Enter #{x+1} '))
    numbers[x] = inp

maximum=numbers[0]

for x in numbers:
    if maximum<x:
        maximum=x

print("Max number is :" ,maximum)

Enter #1 44
Enter #2 55
Enter #3 22
Max number is : 55.0


## 1.3] Write a program to swap the values of two variables without using temporary variable.

In [17]:
a, b = 1, 2
print('Before swapping \na :', a, '\nb :', b)
a, b = b, a
print('\nAfter swapping \na :', a, '\nb :', b)

Before swapping 
a : 1 
b : 2

After swapping 
a : 2 
b : 1


## 1.4] Write a program to implement calculator.

In [59]:
from IPython.display import clear_output 



while True:
    print('1) Add\n2) Subtract\n3) Multiply\n4) Divide\n5) Exit')
    choice = int(input('Enter your choice '))
    
    
    if choice in [1, 2, 3, 4]:
        if choice is 1:
            print('ADDITION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '+', b, '=', a+b)
        
        if choice is 2:
            print('SUBTRACTION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '-', b, '=', a-b)

        if choice is 3:
            print('MULTIPLICATION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '*', b, '=', a*b)
        
        if choice is 4:
            print('DIVISION\n')
            a = int(input('Enter number '))
            b = int(input('Enter number '))
            print(a, '/', b, '=', a/b)

    elif choice is 5:
        break
    else:
        print('Invalid Input\n')

1) Add
2) Subtract
3) Multiply
4) Divide
5) Exit
Enter your choice 3
MULTIPLICATION

Enter number 22
Enter number 1
22 * 1 = 22
1) Add
2) Subtract
3) Multiply
4) Divide
5) Exit
Enter your choice 5


## 1.5] Write a Python program to calculate the sum of the digits in an integer.

In [60]:
num = int(input("Your number (must be 4 digit) : "))
x = num//1000
x1 = (num - x*1000)//100
x2 = (num - x*1000 - x1*100)//10
x3 = (num - x*1000 - x1*100 - x2*10)

print(f'sum of number\'s digits : {x+x1+x2+x3}')

Your number (must be 4 digit) : 1234
sum of number's digits : 10


# 2] Introduction to Control Structures and Functions
---

## 2.1] Write  a  program  to  find factorial  of  a  given  number  using  iterative  and recursive function.

### 2.1.1] Iterative method to find factorial of given number.

In [61]:
n=int(input("Enter Number : "))
fact=1

while(n>0):
  fact*=n
  n-=1

print(fact)

Enter Number : 4
24


### 2.1.2] Recursive method to find factorial of given number.

In [62]:
n=int(input('Enter number : '))

def find_fac(num):
  if num==0:
    return 1
  else:
    return num*find_fac(num-1)

print(find_fac(n))

Enter number : 4
24


## 2.2] Write a program to check whether a given number is prime or not.

In [63]:
n=int(input('Enter Number :'))

def is_prime(num):
  flag=0
  for x in range(1, num+1):
    if num%x==0:
      flag+=1

  if flag==2:
    print(num, 'is Prime')
  else:
    print(num, 'is not prime')

is_prime(n)


Enter Number :4
4 is not prime


## 2.3] Write a program to print Fibonacci series upto n. 

In [64]:
n = int(input("How many terms? "))

a, b = 0, 1
count = 0

if n <= 0:
   print("Please enter a positive integer")
elif n == 1:
   print(a)
else:
   while count < n:
       print(a)
       c = a + b
       a = b
       b = c
       count += 1

How many terms? 5
0
1
1
2
3


## 2.4] Write a program which takes a sentence from user and calculates number of digits, letters, uppercase letters, lowercase letter and spaces in sentence.

In [65]:
def Count(str):
    upper, lower, digit, space = 0, 0, 0, 0
    for i in range(len(str)):
        if str[i].isupper():
          upper += 1
        elif str[i].islower():
          lower += 1
        elif str[i].isdigit():
          digit += 1
        elif str[i] == ' ':
          space += 1
    print('Total letters:', upper + lower)
    print('Upper case letters:', upper)
    print('Lower case letters:', lower)
    print('Number of digits:',digit)
    print('Spaces :', space)

teststr = str(input('enter string :\n')) 
Count(teststr)

enter string :
Ajay Pathak 22
Total letters: 10
Upper case letters: 2
Lower case letters: 8
Number of digits: 2
Spaces : 2


## 2.5] Reversing a given string.

In [66]:
str_to_reverse = str(input('Enter String : \n'))
print('original string : \n', str_to_reverse)
print('Reveresed string : \n', str_to_reverse[::-1])

Enter String : 
Try to reverse this string
original string : 
 Try to reverse this string
Reveresed string : 
 gnirts siht esrever ot yrT


# 3] Study of List and Tuple
---

## 3.1] Write a program to remove duplicates from list.

In [68]:
myList = ['One', 'two', 'two', 'three', 'three', 'three', 'four']
unique = []

print('original list :', myList)

for el in myList:
    if el not in unique:
        unique.append(el)

print('without duplicates :', unique)

original list : ['One', 'two', 'two', 'three', 'three', 'three', 'four']
without duplicates : ['One', 'two', 'three', 'four']


## 3.2] Write a program to find frequency of elements of list.

In [69]:
my_list = [7, 2, 6, 5, 8, 7, 8, 3, 2, 3]
unique = []
for el in my_list:
    if el not in unique:
        unique.append(el)

for el in unique:
    print('Frequency of ', el, 'in my_list :', my_list.count(el))

Frequency of  7 in my_list : 2
Frequency of  2 in my_list : 2
Frequency of  6 in my_list : 1
Frequency of  5 in my_list : 1
Frequency of  8 in my_list : 2
Frequency of  3 in my_list : 2


## 3.3] Write a program to sort given list.

In [70]:
print('Original :', my_list)
my_list.sort()
print('Ascending :', my_list)
print('Descending :', my_list[::-1])

Original : [7, 2, 6, 5, 8, 7, 8, 3, 2, 3]
Ascending : [2, 2, 3, 3, 5, 6, 7, 7, 8, 8]
Descending : [8, 8, 7, 7, 6, 5, 3, 3, 2, 2]


## 3.4] Write a program to find minimum and maximum value in list of tuples.

In [71]:
my_tuple_list = [(22, 1), (16, 3), (27, 11), (29, 9)]
print('Original list :', my_tuple_list)

zeroth = [tup[0] for tup in my_tuple_list]
first = [tup[1] for tup in my_tuple_list]

print(max(zeroth))
res1 = min(zeroth), max(zeroth)
res2 = min(first), max(first)
print('\nmin at 0th index of tuples :', res1[0], '\nmax at 0th index of tuples :', res1[1])
print('\nmin at 1st index of tuples :', res2[0], '\nmax at 1st index of tuples :', res2[1])

Original list : [(22, 1), (16, 3), (27, 11), (29, 9)]


TypeError: ignored

## 3.5] Write a program to remove an element from tuple. 

In [72]:
myTuple = ('one', 'two', 'three', 'four', 'four', 'five')
print(myTuple)

('one', 'two', 'three', 'four', 'four', 'five')


In [73]:
# Removing element using slicing
myTuple = myTuple[:3] + myTuple[4:]
print(myTuple)

('one', 'two', 'three', 'four', 'five')


In [74]:
# Removing using typecast
myList = list(myTuple)
myList.remove('four')
myTuple = myList
print(myTuple)

['one', 'two', 'three', 'five']


# 4] Study of Dictionary
---

## 4.1] Write a program to map 2 lists into a dictionary.

In [75]:
l1 = [1, 2, 3, 4, 5]
l2 = ['one', 'two', 'three', 'four', 'five']

d1 = dict(zip(l1, l2))

print(d1)


{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}


## 4.2] Write  a  program  to  generate  dictionary  of  frequency  of  alphabets  of  given string.

In [76]:
string = str(input("Enter string : "))
keys = []
values = []

for el in string:
    if el not in keys:
        keys.append(el)
        values.append(string.count(el))

d1 = dict(zip(keys, values))
print(d1)

Enter string : Ajay 
{'A': 1, 'j': 1, 'a': 1, 'y': 1, ' ': 1}


## 4.3] Write a Python program to sum all the items in a dictionary.

In [77]:
d1 = {'hundred': 100, 'sixty': -60, 'twenty': -20, 'two': 2}
sum = int(sum(d1.values()))
print(sum)

22


## 4.4]Create a dictionary where keys are name of students and values are another dictionary containing semester, age and cpi of that student. 


In [78]:
student_info = {'Ak': {'semester': 5,
                       'age': 19,
                       'cpi': 8.2},
                'Aj': {'semester': 5,
                       'age': 20,
                       'cpi': 9.0}}

### 4.4.1] Print all the names of students.

In [79]:
print(student_info)

{'Ak': {'semester': 5, 'age': 19, 'cpi': 8.2}, 'Aj': {'semester': 5, 'age': 20, 'cpi': 9.0}}


### 4.4.2] Print only names of students

In [80]:
print(student_info.keys())

dict_keys(['Ak', 'Aj'])


### 4.4.3] Print the name of student having highest CPI 

In [81]:
names = [x for x in student_info]

cpis = [student_info.get(name).get('cpi') for name in names]
highest = max(cpis)

pos = cpis.index(highest)
print('Student havning highest cpi :', names[pos])


TypeError: ignored

## 4.5] Nested Dictionary Practice


### 4.5.1] Creating a Nested Dictionary

In [82]:
faculty = {1: {'name': 'Akj', 'contact': 1234567890, 'city': 'city1'},
           2: {'name': 'sk', 'contact': 9987654321, 'city': 'city1'},
           3: {'name': 'ap', 'contact': 1234509876, 'city': 'city2'}}

print(faculty)

{1: {'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}, 2: {'name': 'sk', 'contact': 9987654321, 'city': 'city1'}, 3: {'name': 'ap', 'contact': 1234509876, 'city': 'city2'}}


### 4.5.2] Accessing elements

In [83]:
print(faculty[1]['name'])
print(faculty[2]['contact'])
print(faculty[3]['city'])

for x in faculty.keys():
  print(faculty[x])

Akj
9987654321
city2
{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'ap', 'contact': 1234509876, 'city': 'city2'}


### 4.5.3] Adding element 

In [84]:
faculty[4] = {}
faculty[4]['name'] = 'SP'
# faculty[4]['contact'] = 5432109876
faculty[4]['city'] = 'city2'

faculty[5] = {'name': 'LK', 'contact': 5647382910, 'city': 'city2', 'married': 'yes'}

for x in faculty.keys():
  print(faculty[x])

{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'ap', 'contact': 1234509876, 'city': 'city2'}
{'name': 'SP', 'city': 'city2'}
{'name': 'LK', 'contact': 5647382910, 'city': 'city2', 'married': 'yes'}


### 4.5.4] Deleting elemets

In [85]:
del faculty[5]['married']
del faculty[3], faculty[4]

for key in faculty.keys():
  print(faculty[key])


{'name': 'Akj', 'contact': 1234567890, 'city': 'city1'}
{'name': 'sk', 'contact': 9987654321, 'city': 'city1'}
{'name': 'LK', 'contact': 5647382910, 'city': 'city2'}


### 4.5.5] Iterating through Nested Dictionary

In [86]:
for id, value in faculty.items():
  print('Faculty ID =', id)

  for key in value:
    print(key, '=', value[key])
  print('\n')

Faculty ID = 1
name = Akj
contact = 1234567890
city = city1


Faculty ID = 2
name = sk
contact = 9987654321
city = city1


Faculty ID = 5
name = LK
contact = 5647382910
city = city2




# 5] Write a python program to explore various types of files (csv, excel etc.) using pandas.
---

## Importing Pandas and defining data.

First of all ,

To use pandas library, we need to install pandas and import it.

Conventionally we use alias 'pd' for pandas library 

In [87]:
import pandas as pd

Next cell defines data 

we are using data of different countries ( such as population, GDP, Continent etc.) 

In [88]:
contries_data = {
    'CHN': {'COUNTRY': 'China', 'POP': 1_398.72, 'AREA': 9_596.96,
            'GDP': 12_234.78, 'CONT': 'Asia'},
    'IND': {'COUNTRY': 'India', 'POP': 1_351.16, 'AREA': 3_287.26,
            'GDP': 2_575.67, 'CONT': 'Asia', 'IND_DAY': '1947-08-15'},
    'USA': {'COUNTRY': 'US', 'POP': 329.74, 'AREA': 9_833.52,
            'GDP': 19_485.39, 'CONT': 'N.America',
            'IND_DAY': '1776-07-04'},
    'IDN': {'COUNTRY': 'Indonesia', 'POP': 268.07, 'AREA': 1_910.93,
            'GDP': 1_015.54, 'CONT': 'Asia', 'IND_DAY': '1945-08-17'},
    'BRA': {'COUNTRY': 'Brazil', 'POP': 210.32, 'AREA': 8_515.77,
            'GDP': 2_055.51, 'CONT': 'S.America', 'IND_DAY': '1822-09-07'},
    'PAK': {'COUNTRY': 'Pakistan', 'POP': 205.71, 'AREA': 881.91,
            'GDP': 302.14, 'CONT': 'Asia', 'IND_DAY': '1947-08-14'},
    'NGA': {'COUNTRY': 'Nigeria', 'POP': 200.96, 'AREA': 923.77,
            'GDP': 375.77, 'CONT': 'Africa', 'IND_DAY': '1960-10-01'},
    'BGD': {'COUNTRY': 'Bangladesh', 'POP': 167.09, 'AREA': 147.57,
            'GDP': 245.63, 'CONT': 'Asia', 'IND_DAY': '1971-03-26'},
    'RUS': {'COUNTRY': 'Russia', 'POP': 146.79, 'AREA': 17_098.25,
            'GDP': 1_530.75, 'IND_DAY': '1992-06-12'},
    'MEX': {'COUNTRY': 'Mexico', 'POP': 126.58, 'AREA': 1_964.38,
            'GDP': 1_158.23, 'CONT': 'N.America', 'IND_DAY': '1810-09-16'},
    'JPN': {'COUNTRY': 'Japan', 'POP': 126.22, 'AREA': 377.97,
            'GDP': 4_872.42, 'CONT': 'Asia'},
    'DEU': {'COUNTRY': 'Germany', 'POP': 83.02, 'AREA': 357.11,
            'GDP': 3_693.20, 'CONT': 'Europe'},
    'FRA': {'COUNTRY': 'France', 'POP': 67.02, 'AREA': 640.68,
            'GDP': 2_582.49, 'CONT': 'Europe', 'IND_DAY': '1789-07-14'},
    'GBR': {'COUNTRY': 'UK', 'POP': 66.44, 'AREA': 242.50,
            'GDP': 2_631.23, 'CONT': 'Europe'},
    'ITA': {'COUNTRY': 'Italy', 'POP': 60.36, 'AREA': 301.34,
            'GDP': 1_943.84, 'CONT': 'Europe'},
    'ARG': {'COUNTRY': 'Argentina', 'POP': 44.94, 'AREA': 2_780.40,
            'GDP': 637.49, 'CONT': 'S.America', 'IND_DAY': '1816-07-09'},
    'DZA': {'COUNTRY': 'Algeria', 'POP': 43.38, 'AREA': 2_381.74,
            'GDP': 167.56, 'CONT': 'Africa', 'IND_DAY': '1962-07-05'},
    'CAN': {'COUNTRY': 'Canada', 'POP': 37.59, 'AREA': 9_984.67,
            'GDP': 1_647.12, 'CONT': 'N.America', 'IND_DAY': '1867-07-01'},
    'AUS': {'COUNTRY': 'Australia', 'POP': 25.47, 'AREA': 7_692.02,
            'GDP': 1_408.68, 'CONT': 'Oceania'},
    'KAZ': {'COUNTRY': 'Kazakhstan', 'POP': 18.53, 'AREA': 2_724.90,
            'GDP': 159.41, 'CONT': 'Asia', 'IND_DAY': '1991-12-16'}
}

columns = ('COUNTRY', 'POP', 'AREA', 'GDP', 'CONT', 'IND_DAY')

## Using pandas DataFrame 

DataFrame is pandas way of storing and visiualizing data

to convert our dictionary ( or any DataStructure ) in pandas DataFrame object , we use ```pd.DataFrame(data_variable_name)```.

It returns our data in DataFrame format , so we need to store it in some variable.

In [89]:
# We stored our data in 'contries_data' variable
# Let's store the returned DataFrame Object in df (DataFrame)
df = pd.DataFrame(contries_data)

# we can use print function
print(df)

             CHN         IND         USA  ...         CAN        AUS         KAZ
COUNTRY    China       India          US  ...      Canada  Australia  Kazakhstan
POP      1398.72     1351.16      329.74  ...       37.59      25.47       18.53
AREA     9596.96     3287.26     9833.52  ...     9984.67    7692.02      2724.9
GDP      12234.8     2575.67     19485.4  ...     1647.12    1408.68      159.41
CONT        Asia        Asia   N.America  ...   N.America    Oceania        Asia
IND_DAY      NaN  1947-08-15  1776-07-04  ...  1867-07-01        NaN  1991-12-16

[6 rows x 20 columns]


In [90]:
# We are not getting whole data , also representation is not good 
# Let's use something better
# We can directly call our dataframe object and it will print the data 
df

CHN         IND         USA  ...         CAN        AUS         KAZ
COUNTRY    China       India          US  ...      Canada  Australia  Kazakhstan
POP      1398.72     1351.16      329.74  ...       37.59      25.47       18.53
AREA     9596.96     3287.26     9833.52  ...     9984.67    7692.02      2724.9
GDP      12234.8     2575.67     19485.4  ...     1647.12    1408.68      159.41
CONT        Asia        Asia   N.America  ...   N.America    Oceania        Asia
IND_DAY      NaN  1947-08-15  1776-07-04  ...  1867-07-01        NaN  1991-12-16

[6 rows x 20 columns]

In [91]:
# Much better but , Let's also transpose it. To make it more intuitive. 
df = pd.DataFrame(contries_data, index=columns).T # Notice, using .T results in transposing the data
df

COUNTRY      POP     AREA      GDP       CONT     IND_DAY
CHN       China  1398.72  9596.96  12234.8       Asia         NaN
IND       India  1351.16  3287.26  2575.67       Asia  1947-08-15
USA          US   329.74  9833.52  19485.4  N.America  1776-07-04
IDN   Indonesia   268.07  1910.93  1015.54       Asia  1945-08-17
BRA      Brazil   210.32  8515.77  2055.51  S.America  1822-09-07
PAK    Pakistan   205.71   881.91   302.14       Asia  1947-08-14
NGA     Nigeria   200.96   923.77   375.77     Africa  1960-10-01
BGD  Bangladesh   167.09   147.57   245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.2  1530.75        NaN  1992-06-12
MEX      Mexico   126.58  1964.38  1158.23  N.America  1810-09-16
JPN       Japan   126.22   377.97  4872.42       Asia         NaN
DEU     Germany    83.02   357.11   3693.2     Europe         NaN
FRA      France    67.02   640.68  2582.49     Europe  1789-07-14
GBR          UK    66.44    242.5  2631.23     Europe         NaN
ITA       Italy    60.36   301.34  1943.84     Europe         NaN
ARG   Argentina    44.94   2780.4   637.49  S.America  1816-07-09
DZA     Algeria    43.38  2381.74   167.56     Africa  1962-07-05
CAN      Canada    37.59  9984.67  1647.12  N.America  1867-07-01
AUS   Australia    25.47  7692.02  1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.9   159.41       Asia  1991-12-16

## Using Pandas to convert data in various format types.

### CSV Format type

Use ```to_csv('file_name.csv')``` to convert DataFrame in CSV format

In [92]:
# Let's convert our contries_data into csv format
# our contries data is stored in df variable 
df.to_csv('contries_data.csv')  # NOTE : we give the filename whatever we like but its extension must be .csv

# if you check your colab folder , 
# you can see contries_data.csv file.

Use ```pd.read_csv(filename)``` to read csv file.

This function returns DataFrame object , so we need to store it in some variable.

In [93]:
df = pd.read_csv('contries_data.csv') # NOTE : Only file with extension .csv can be read. 
# Now that it returns DataFrame object , we can print it like below
df

Unnamed: 0     COUNTRY      POP      AREA       GDP       CONT     IND_DAY
0         CHN       China  1398.72   9596.96  12234.78       Asia         NaN
1         IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
2         USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
3         IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
4         BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
5         PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
6         NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
7         BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
8         RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
9         MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
10        JPN       Japan   126.22    377.97   4872.42       Asia         NaN
11        DEU     Germany    83.02    357.11   3693.20     Europe         NaN
12        FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
13        GBR          UK    66.44    242.50   2631.23     Europe         NaN
14        ITA       Italy    60.36    301.34   1943.84     Europe         NaN
15        ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
16        DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
17        CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
18        AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
19        KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

In [94]:
# Let's make column that represents country's abbreviated names as a index column
# in read_csv fumction we can give index which represents index
# in our case first column represents index , so it's 0th column in DataFrame
df = pd.read_csv('contries_data.csv', index_col=0) 
df

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia         NaN
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia         NaN
DEU     Germany    83.02    357.11   3693.20     Europe         NaN
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe         NaN
ITA       Italy    60.36    301.34   1943.84     Europe         NaN
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### Excel format type

To convert to and read from Excel files we need to install some packages. 
- xlwt
- openpyxl
- xlswriter
- xlrd

NOTE : Below cell gives command to install these in one line only

We can always install only one package and not others if not required

In [95]:
pip install xlwt openpyxl xlsxwriter xlrd

In [96]:
df.to_excel('contries_data.xlsx')

# We can find this file in our colab folder

In [97]:
df = pd.read_excel('contries_data.xlsx', index_col=0)
df

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia         NaN
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia         NaN
DEU     Germany    83.02    357.11   3693.20     Europe         NaN
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe         NaN
ITA       Italy    60.36    301.34   1943.84     Europe         NaN
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania         NaN
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### JSON format type

In [98]:
df_json = df.to_json('contries_data.json')

# New jason file will be added in your directory
pd.read_json('contries_data.json')

COUNTRY      POP      AREA       GDP       CONT     IND_DAY
CHN       China  1398.72   9596.96  12234.78       Asia        None
IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
RUS      Russia   146.79  17098.25   1530.75       None  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
JPN       Japan   126.22    377.97   4872.42       Asia        None
DEU     Germany    83.02    357.11   3693.20     Europe        None
FRA      France    67.02    640.68   2582.49     Europe  1789-07-14
GBR          UK    66.44    242.50   2631.23     Europe        None
ITA       Italy    60.36    301.34   1943.84     Europe        None
ARG   Argentina    44.94   2780.40    637.49  S.America  1816-07-09
DZA     Algeria    43.38   2381.74    167.56     Africa  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  N.America  1867-07-01
AUS   Australia    25.47   7692.02   1408.68    Oceania        None
KAZ  Kazakhstan    18.53   2724.90    159.41       Asia  1991-12-16

### HTML format type

In [99]:
df_html = df.to_html('contries_data.html')

# New jason file will be added in your directory
pd.read_html('contries_data.html')

[   Unnamed: 0     COUNTRY      POP      AREA       GDP       CONT     IND_DAY
 0         CHN       China  1398.72   9596.96  12234.78       Asia         NaN
 1         IND       India  1351.16   3287.26   2575.67       Asia  1947-08-15
 2         USA          US   329.74   9833.52  19485.39  N.America  1776-07-04
 3         IDN   Indonesia   268.07   1910.93   1015.54       Asia  1945-08-17
 4         BRA      Brazil   210.32   8515.77   2055.51  S.America  1822-09-07
 5         PAK    Pakistan   205.71    881.91    302.14       Asia  1947-08-14
 6         NGA     Nigeria   200.96    923.77    375.77     Africa  1960-10-01
 7         BGD  Bangladesh   167.09    147.57    245.63       Asia  1971-03-26
 8         RUS      Russia   146.79  17098.25   1530.75        NaN  1992-06-12
 9         MEX      Mexico   126.58   1964.38   1158.23  N.America  1810-09-16
 10        JPN       Japan   126.22    377.97   4872.42       Asia         NaN
 11        DEU     Germany    83.02    357.11   3693

# 6] Write python programs demonstrating different functions for pre-processing the data. 
---

## NumPy Random

import statement

In [100]:
import numpy as np

### rand() function

```rand()``` function returns random value between 0 to 1.

as it returns the value we need to store it in some variable

In [101]:
# Storing returned value from rand() to r1
r1 = np.random.rand()
print(r1)

0.5618170004362452


We can also specify shape of matrix as an argument values in ```rand()``` function.

In [102]:
random_mat = np.random.rand(2, 2)
# returns matrix of shape given in argument,
# with all the elements having random value between 0 to 1
print(random_mat)

[[0.06399864 0.35633226]
 [0.85798277 0.90875931]]


### randint() function

```randint(start, stop, size)``` 

Returns array of size ```size``` , containing random integers from start to stop exclusive ( meaning stop is not included )

In [103]:
# Here, this will return 20 random integer values from 11 to 20 exclusive
r1 = np.random.randint(11, 20, 20)

print(r1)

[17 14 16 12 14 15 17 19 17 12 15 14 19 19 18 11 13 14 12 13]


In [104]:
# then we can reshape this array and use it as matrix 
r1_mat = r1.reshape(5, 4)
# NOTE reshape returns matrix of shape we give , it doesn't change r1 itself
print('r1 still same :', r1)
print('r1_mat :\n', r1_mat)

r1 still same : [17 14 16 12 14 15 17 19 17 12 15 14 19 19 18 11 13 14 12 13]
r1_mat :
 [[17 14 16 12]
 [14 15 17 19]
 [17 12 15 14]
 [19 19 18 11]
 [13 14 12 13]]


### randn() function

Till now our random values were being selected from uniform distribution ,

using ```randn()``` function , we can select random values from normal distribution

In [105]:
# Use randn function to get random values from normal distribution
normal_dist_random = np.random.randn(3)
print(normal_dist_random)

[-0.64072413 -1.08478321 -0.36273418]


Here is the visualization of both the function ,
We will have 100000 random values from uniform distribution as welll as normal distribution and then we will plot hist diagrams for both of them.

In [106]:
import matplotlib.pyplot as plt
sample_size = 100000
uniform_dist_rand = np.random.rand(sample_size)
normal_dist_rand = np.random.randn(sample_size)

plt.hist(uniform_dist_rand, bins=100)
plt.title('random values from uniform distribution')
plt.show()

plt.hist(normal_dist_rand, bins=100)
plt.title('random values from normal distribution')
plt.show()

As you can see , first graph is of uniformly distributed random values and that is why it resembles uniform distribution....

whereas in 2nd graph we used random values from normal distribution that is why 
it resembles normal distributin...

## Aggregation Functions

Import statement

In [107]:
import numpy as np

In [108]:
# Let's define some data and then use some numpy functions
# This is simple array 
data = [22, 16, 29, 27 , 20, 31, 20, 9]
# let's convert it into nd numpy array
data = np.array(data) # we use np.array(your_array_variable) to convert your array variable in numpy array
print(data, type(data))

[22 16 29 27 20 31 20  9] <class 'numpy.ndarray'>


```min()``` function returns minimum value from the array

In [109]:
print('min value :', data.min())

min value : 9


```argmin()``` returns index of minimum value 

In [110]:
print('min index:', data.argmin())

min index: 7


```max()``` returns maximum value from the array

In [111]:
print('max :', data.max())

max : 31


```argmax()``` returns index of maximum value

In [112]:
print('max index :', data.argmax())

max index : 5


```mean()``` returns mean of all values in array

In [113]:
print('mean :', data.mean())

mean : 21.75


```std()``` returns standard deviation

In [114]:
print('standard deviation :', data.std())

standard deviation : 6.777720855862979


```sum()``` returns sum of elements

using axis argument with aggregation functions


In [115]:
# We can provide axis argument with all the aggregation function we have seen till now
# it defines along which axis we want to perfom certain functions

# To understand properly we need matrix 
# Let's create it
mat = np.random.randint(1, 10, 25) # Getting 25 random integer values from 1 to 100 not inclusive
# reshaping the array into matrix of shape 5x5 , 
# here no of elements much be 25 as we have 25 elements in array 
# that's why i have selected 5x5 shape
mat = mat.reshape(5, 5) 
print(mat)

[[8 2 3 2 5]
 [6 9 8 1 6]
 [4 9 1 6 1]
 [5 5 1 6 9]
 [4 3 4 1 5]]


axis 1 represents rows

In [116]:
print('sum of rows :', mat.sum(axis=1))

sum of rows : [20 30 21 26 17]


axis 0 represents columns

In [117]:
print('sum of columns :', mat.sum(axis=0))

sum of columns : [27 28 17 16 26]


not providing axis includes all the elements

In [118]:
print('sum of all elements :', mat.sum())

sum of all elements : 114


## Slicing of ndarray

In [119]:
# This variable stores birthday of persons
data = [['AJ', 22, 1],
        ['Ace', 16, 3],
        ['Dave', 27, 11],
        ['Lotte', 29, 9],
        ['martha', 20, 6],
        ['steve', 31, 10],
        ['Raj', 9, 10],
        ['Wane', 20, 1]]

print(data)

[['AJ', 22, 1], ['Ace', 16, 3], ['Dave', 27, 11], ['Lotte', 29, 9], ['martha', 20, 6], ['steve', 31, 10], ['Raj', 9, 10], ['Wane', 20, 1]]


```Array[start:stop:step}]```

it returns array starting from index ```start``` till index ```stop``` - 1 , taking ```step``` steps every time. 


Not providing ```start``` argument results in 0, meaning it start from the first element.

In [120]:
print(data[:5]) 

[['AJ', 22, 1], ['Ace', 16, 3], ['Dave', 27, 11], ['Lotte', 29, 9], ['martha', 20, 6]]



Not providing ```stop``` argument results in length of the array.

In [121]:
print(data[5:]) # returns every element from index 5 till last index

[['steve', 31, 10], ['Raj', 9, 10], ['Wane', 20, 1]]


In [122]:
print(data[::2]) 
# Instead of taking one step which is default , it will take 2 steps every time 

[['AJ', 22, 1], ['Dave', 27, 11], ['martha', 20, 6], ['Raj', 9, 10]]


In [123]:
print(data[:-4:-1]) 
# negative stop index means 4th index from the last
# negative steps means reverse traversing 

[['Wane', 20, 1], ['Raj', 9, 10], ['steve', 31, 10]]


In [124]:
print(data)

[['AJ', 22, 1], ['Ace', 16, 3], ['Dave', 27, 11], ['Lotte', 29, 9], ['martha', 20, 6], ['steve', 31, 10], ['Raj', 9, 10], ['Wane', 20, 1]]


Slicing is mutable


In [125]:
array = np.array([1, 2, 3, 4, 5])

# we store last 3 elements values in array_slice variable
array_slice = array[2:]

print(array_slice)

[3 4 5]


In [126]:
# now , we change all the elements in that array_slice variable
array_slice[:] = 0

# it also changes original array's last 3 elements
print('original array :', array)
print('sliced array :', array_slice)

original array : [1 2 0 0 0]
sliced array : [0 0 0]


## Numpy Arithmetic Operations

In [127]:
arr1 = np.random.randint(1, 10, 20)
arr1 = arr1.reshape(5, 4)
arr2 = np.random.randint(1, 10, 20)
arr2 = arr2.reshape(5, 4)

print('arr1 :\n', arr1, '\n\narr2 :\n', arr2)

arr1 :
 [[8 9 7 7]
 [3 2 3 3]
 [8 1 6 4]
 [3 7 1 9]
 [7 9 3 7]] 

arr2 :
 [[2 5 8 2]
 [2 2 2 2]
 [9 4 1 1]
 [3 1 4 4]
 [2 7 9 1]]


In [128]:
# Adding scalar to the matrix
# scalar value is added to every element 

arr1add2 = arr1 + 2
print(arr1add2)

# Substracting scalar value works same 
new_arr = arr1add2 - 2
print(new_arr)

[[10 11  9  9]
 [ 5  4  5  5]
 [10  3  8  6]
 [ 5  9  3 11]
 [ 9 11  5  9]]
[[8 9 7 7]
 [3 2 3 3]
 [8 1 6 4]
 [3 7 1 9]
 [7 9 3 7]]


In [129]:
# Adding both matrices
sum_mat = arr1 + arr2
print(sum_mat)

[[10 14 15  9]
 [ 5  4  5  5]
 [17  5  7  5]
 [ 6  8  5 13]
 [ 9 16 12  8]]


In [130]:
sub_mat = sum_mat - arr2
# Our ans should be same as arr1
print(sub_mat)

[[8 9 7 7]
 [3 2 3 3]
 [8 1 6 4]
 [3 7 1 9]
 [7 9 3 7]]


In [131]:
# Division works same
arr1div2 = arr1 / 2
print(arr1div2)

[[4.  4.5 3.5 3.5]
 [1.5 1.  1.5 1.5]
 [4.  0.5 3.  2. ]
 [1.5 3.5 0.5 4.5]
 [3.5 4.5 1.5 3.5]]


In [132]:
# We can perform elementwise division between matrices as follow
div = arr1/arr2
print(div)

[[4.         1.8        0.875      3.5       ]
 [1.5        1.         1.5        1.5       ]
 [0.88888889 0.25       6.         4.        ]
 [1.         7.         0.25       2.25      ]
 [3.5        1.28571429 0.33333333 7.        ]]


In [133]:
# same goes for multiplication
# Multiplying arr2 with our div variable should return arr1
new_arr = div * arr2
print(new_arr)

[[8. 9. 7. 7.]
 [3. 2. 3. 3.]
 [8. 1. 6. 4.]
 [3. 7. 1. 9.]
 [7. 9. 3. 7.]]


In [134]:
# For matrix multiplication we use matmul function or dot function
# We need to use transpose of one of the array to make them eligible for matrix multiplication
mat_mul = np.matmul(arr1, arr2.T)
print(mat_mul)

[[131  62 122  89 149]
 [ 46  22  41  35  50]
 [ 77  38  86  65  81]
 [ 67  40  65  56  73]
 [ 97  52 109  70 111]]


In [135]:
dot = arr1.dot(arr2.T)
print(dot)

[[131  62 122  89 149]
 [ 46  22  41  35  50]
 [ 77  38  86  65  81]
 [ 67  40  65  56  73]
 [ 97  52 109  70 111]]


In [136]:
using_atRate = arr1 @ arr2.T
print(using_atRate)

[[131  62 122  89 149]
 [ 46  22  41  35  50]
 [ 77  38  86  65  81]
 [ 67  40  65  56  73]
 [ 97  52 109  70 111]]


## Sorting

In [137]:
my_data_type = np.dtype([('name', 'S10'), ('email', 'S10'), ('Gender', 'S10'), ('age', int)]) 

data = np.array([ ('Nate', 'Nate.data@gamil.com', 'Female', 24),
                 ('Aj', 'Aj.data@gmail.com', 'Male', 19),
                 ('Hari', 'Hari.data@gmail.com', 'Male', 23),
                 ('Ace', 'Ace.data@gmail.com', 'Female', 19)], dtype=my_data_type)



print(data)

[(b'Nate', b'Nate.data@', b'Female', 24)
 (b'Aj', b'Aj.data@gm', b'Male', 19) (b'Hari', b'Hari.data@', b'Male', 23)
 (b'Ace', b'Ace.data@g', b'Female', 19)]


In [138]:
data.sort(order='name')
print(data)

[(b'Ace', b'Ace.data@g', b'Female', 19)
 (b'Aj', b'Aj.data@gm', b'Male', 19) (b'Hari', b'Hari.data@', b'Male', 23)
 (b'Nate', b'Nate.data@', b'Female', 24)]


In [139]:
data.sort(order=['Gender', 'name', 'age'])
print(data)

[(b'Ace', b'Ace.data@g', b'Female', 19)
 (b'Nate', b'Nate.data@', b'Female', 24)
 (b'Aj', b'Aj.data@gm', b'Male', 19) (b'Hari', b'Hari.data@', b'Male', 23)]


## Conditional Selection

In [140]:
numbers = np.random.randn(20)
print(numbers)

[-1.24681341 -1.5007142   0.97990707 -1.72820462 -0.16591694 -0.74647989
 -0.7585243  -0.49549122 -1.45415317 -1.6945704   1.49049821 -1.07083627
 -1.5519479  -0.15992297 -0.78085532  1.1143071   0.95635114 -0.2177909
 -1.62601492  0.23641451]


In [141]:
# Lets make bool array to represent negative and positive elements
# negative numbers would ne false and positive would be true

sign = numbers > 0
print(sign)

[False False  True False False False False False False False  True False
 False False False  True  True False False  True]


## Pandas Series

In [142]:
import pandas as pd
import numpy as np

In [143]:
s = pd.Series([1, 2, 4, 6, 7, 0])
print(s)

0    1
1    2
2    4
3    6
4    7
5    0
dtype: int64


In [144]:
print('3rd element in series :', s[2])
print('2nd last element in series :', s[4])

3rd element in series : 4
2nd last element in series : 7


In [145]:
sum = s[3] + s[1]
print(sum)

8


In [146]:
data = pd.Series(np.random.randint(0, 51, 7), dtype=str)
print(data)

0    47
1     2
2    13
3    31
4     6
5     8
6    46
dtype: object


In [147]:
indeces = ['Emp. Id', 'Name', 'Post']
emp_data = [12.1, 'Nate', 'R4']
emp_data_S = pd.Series(data=emp_data, index=indeces)
print(emp_data_S)


Emp. Id    12.1
Name       Nate
Post         R4
dtype: object


## Creating Time series


In [148]:
import pandas as pd
import numpy as np

In [149]:
date = pd.to_datetime("22nd of January , 2002")
daily_indeces = date + pd.to_timedelta(np.arange(20), unit='D')
data = np.random.randn(20) > 0

stock_trend = pd.Series(data=data, index=daily_indeces)
print(stock_trend)

2002-01-22    False
2002-01-23     True
2002-01-24     True
2002-01-25    False
2002-01-26    False
2002-01-27    False
2002-01-28     True
2002-01-29     True
2002-01-30     True
2002-01-31     True
2002-02-01    False
2002-02-02     True
2002-02-03    False
2002-02-04     True
2002-02-05    False
2002-02-06     True
2002-02-07    False
2002-02-08     True
2002-02-09     True
2002-02-10     True
dtype: bool


# 7] Demonstrate Statistical data analysing Numeric Data in python.
---

importing numpy

In [150]:
import numpy as np


Creating array ussing numpy array() method
we used random.randint() method to generate 5 random elements from [0, 10)

In [151]:
arr1 = np.array(np.random.randint(0, 10, 5))
print(arr1)

[4 9 2 4 8]


Accessing and manipulating array elements 

In [152]:
print(arr1[3]) # prints elememt on 3rd index from arr 

4


In [153]:
print('arr1 before changing value : ',arr1)
arr1[3] = arr1[2] # changes value of 3rd index to the value of 2nd index in arr1
print('arr1 after changing value : ',arr1)

arr1 before changing value :  [4 9 2 4 8]
arr1 after changing value :  [4 9 2 2 8]


Let's create 2D array 


In [154]:
# arr2 = np.random.randint(0, 10, 3)
# arr3 = np.arange(0, 5)
# matrix1 = np.array([arr2, [1, 3, 5]], dtype=int)
# print(matrix1)

matrix = np.array([ [22, 16, 27], 
                    [1, 3, 11] ])
print(matrix)

[[22 16 27]
 [ 1  3 11]]


We can know the size of the matrix/array with shape method in numpy

In [155]:
print(matrix.shape)

(2, 3)


We can access 2D array element as below

In [156]:
print('first element in first row : ', matrix[0][0])
print('last element in last row : ', matrix[-1][-1]) # negative index refers to the list in reverse order
print('second row : ', matrix[1]) # not providing colom value returns whole row

first element in first row :  22
last element in last row :  11
second row :  [ 1  3 11]


Array of type string

In [157]:
family = ['Father', 'Mother', 'Brother', 'Sister']
print(family)
print('3rd element in family list is : ', family[2]) # accessing array element as shown earlier

['Father', 'Mother', 'Brother', 'Sister']
3rd element in family list is :  Brother


Using the arange() and linspace() function to evenly space values in a specified interval.

In [158]:
arr_with_same_difference = np.arange(0, 10, 3)
print('This array will have same difference between adjacent elements : \n', arr_with_same_difference)
# so using arrange method returns list in given range i.e., (0, 10) in our case , with every 3rd element in our case

This array will have same difference between adjacent elements : 
 [0 3 6 9]


In [159]:
# if we want a list of numbers in range (11, 30) with every 5th element 
# we can write
five_diff = np.arange(11, 30, 5)
print(five_diff)

[11 16 21 26]


In [160]:
# Using linspace 
arr = np.linspace(11, 30, 50)
print(arr)

[11.         11.3877551  11.7755102  12.16326531 12.55102041 12.93877551
 13.32653061 13.71428571 14.10204082 14.48979592 14.87755102 15.26530612
 15.65306122 16.04081633 16.42857143 16.81632653 17.20408163 17.59183673
 17.97959184 18.36734694 18.75510204 19.14285714 19.53061224 19.91836735
 20.30612245 20.69387755 21.08163265 21.46938776 21.85714286 22.24489796
 22.63265306 23.02040816 23.40816327 23.79591837 24.18367347 24.57142857
 24.95918367 25.34693878 25.73469388 26.12244898 26.51020408 26.89795918
 27.28571429 27.67346939 28.06122449 28.44897959 28.83673469 29.2244898
 29.6122449  30.        ]


Create an array of constant values in a given shape.

In [161]:
# we can create any size of array with same value in every element with the code below 
# we use full() method and give shape of an array a fist argument and value as second argument
const_arr = np.full((3, 10), 'Naruto')
print(const_arr)
print('shape of this arr is : ', const_arr.shape)

[['Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto'
  'Naruto' 'Naruto']
 ['Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto'
  'Naruto' 'Naruto']
 ['Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto' 'Naruto'
  'Naruto' 'Naruto']]
shape of this arr is :  (3, 10)


 Repeat each element of an array by a specified number of times using repeat() and tile() functions.

In [162]:
# to create new array from existing array with each element repeating specific time 
# we use repeat() method
arr_to_repeat = [22, 21, 20]
repeated_arr = np.repeat(arr_to_repeat, 2)
# here , all the elements of array will be repeated twice
print(repeated_arr)

[22 22 21 21 20 20]


In [163]:
# we use tile() method to repeat whole array specific times
repeating_whole_arr = np.tile(arr_to_repeat, 3)
# here, whole array will be repeated thrice
print(repeating_whole_arr)

[22 21 20 22 21 20 22 21 20]


Create an identity matrix using eye() and identity() function.

In [164]:
# we can use eye() method to Return a 2-D array with ones on the diagonal and zeros elsewhere
eye_arr = np.eye(3)
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [165]:
# similarly, we can use identity() method to Return the identity array.
iden_arr = np.identity(5)
print(iden_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Creating 2D array for random numbers between 0 to 1.

In [166]:
random_matrix = np.random.rand(4, 5)
# we need to give shape of desired array in argument
print(random_matrix)

[[0.26757783 0.42791822 0.73985361 0.88108305 0.82788286]
 [0.88050149 0.00850505 0.39582958 0.19962045 0.29440079]
 [0.90668317 0.87362576 0.07334042 0.42431852 0.14351399]
 [0.2625494  0.1716638  0.45757032 0.38907406 0.80529549]]
